### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [awslabs/aws-sam-cli#1777]
### Description

Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Wall -m py_compile {}

./tests/unit/lib/schemas/test_schemas_api_caller.py:233: DeprecationWarning: invalid escape sequence \/
  "Content": '{"components":{"schemas":{"Some\/Awesome\/Schema.Object.1":{"type":"object","required":["foo","bar","baz"],"properties":{"foo":{"type":"string"},'
./tests/unit/lib/schemas/test_schemas_api_caller.py:234: DeprecationWarning: invalid escape sequence \/
  '"bar":{"type":"string"},"baz":{"type":"string"}}},"Some\/Awesome\/Schema.Object$2":{"type":"object","required":["foo","bar","baz"],'
./tests/integration/init/schemas/schemas_test_data_setup.py:172: DeprecationWarning: invalid escape sequence \/
  '"$ref":"#\/components\/schemas\/aws.partner\/mongodb.com\/Ticket.Created"},"detail-type":{"type":"string"},"resources":{"type":"array",'
```

**Comment by jfuss** [comment]
While we should fix the warnings they are not Python3.8 specific. I also see them in Python3.7.

**Comment by tirkarthi** [comment]
Yes, they were also present in Python 3.7 . In Python 3.8 they were made `SyntaxWarning` but got reverted later to deprecation warning since a lot of libraries were not fixed extending the deprecation period.

**Comment by jfuss** [comment]
@tirkarthi Ahh. That makes more sense! I didn't realize they were reverted back.

**Comment by tirkarthi** [comment]
I will raise a PR for this shortly.

**Comment by jfuss** [comment]
@tirkarthi That would be much appreciated! Thank you!
