### ISSUE TITLE
Global variables are undefined when running local invoke

### ISSUE THREAD

**Issue by alnutile** [awslabs/aws-sam-cli#380]
```
Resources:
  GithubPushes:
    Type: AWS::Serverless::Function
    DependsOn:
      - Stream
    Properties:
      Runtime: nodejs8.10
      Description: >-
        This will verify that the incoming data is from Github and hashed with the key
        we are using for this environment
      Environment:
        Variables:
          SECRET: !Sub ${Secret}
```
works fine when I run 
```
SECRET=foo sam local invoke "GithubPushes" -e fixtures/data.json
```

but if I move that to Globals then this becomes "undefined"

**Comment by sanathkr** [comment]
This is solved in the latest release - https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0.

**Comment by fairct** [comment]
Possibly a regression - but this is not working for me on 0.6.1.
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: nodejs8.10
    Environment:
      Variables:
        subVariable: !Sub "myVariable is now ${myVariableValue}"
        refVariable: !Ref myVariableValue

Parameters:
  myVariableValue:
    Type: String
    Default: blue

Resources:
  LambdaDef:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: .
```

```
exports.handler = function(event, context, callback) {
  console.log("Sub value: " + process.env.myVariable);
  console.log("Ref value: " + process.env.refVariable);
}
```

```
$ echo "{\"stuff\": \"value\"}" | sam local invoke -t template.yml
2018-10-24 10:13:16 Reading invoke payload from stdin (you can also pass it from file with --event)
2018-10-24 10:13:16 Invoking index.handler (nodejs8.10)

Fetching lambci/lambda:nodejs8.10 Docker container image......
2018-10-24 10:13:17 Mounting /Users/cfair as /var/task:ro inside runtime container
START RequestId: 0378e10b-b6de-1ec8-e525-8d6806261cd1 Version: $LATEST
2018-10-24T14:13:18.151Z	0378e10b-b6de-1ec8-e525-8d6806261cd1	Sub value: undefined
2018-10-24T14:13:18.152Z	0378e10b-b6de-1ec8-e525-8d6806261cd1	Ref value: blue
END RequestId: 0378e10b-b6de-1ec8-e525-8d6806261cd1
REPORT RequestId: 0378e10b-b6de-1ec8-e525-8d6806261cd1	Duration: 6.00 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 31 MB
```

**Comment by fairct** [comment]
I see now. I didn't notice that an env var was set in the original issue that was raised here - so thought that a bug came back. Would it be reasonable to open a feature request for this? I haven't dug into the codebase much at all to determine if it's something within my skillset to PR.

**Comment by jfuss** [comment]
@fairct For Sub intrinsic support? We have a couple open issues for different Intrinsic support, #528 is one. 

Taking a look at the PR for [supporting Ref](https://github.com/awslabs/aws-sam-cli/pull/657), might be a good place to start. Happy to help in any way, if you are interesting in taking on Sub support.

**Comment by ktersius** [comment]
For ref. https://whatibroke.com/2019/01/15/overriding-global-variables-aws-sam-local/
